/** MimaTAVERN v1.3.0 Novel narrative memory helpers. */
(() => {
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const arr=v=>Array.isArray(v)?v:[];
  const clone=v=>JSON.parse(JSON.stringify(v));
  const clean=v=>String(v??'').trim();
  const nowIso=()=>new Date().toISOString();
  const stringList=v=>arr(v).map(clean).filter(Boolean);
  function normalizeObjectList(v){return arr(v).filter(x=>x&&typeof x==='object').map(x=>clone(x));}
  function normalizeSummary(s={}){return{overview:clean(s.overview),events:stringList(s.events),characterChanges:normalizeObjectList(s.characterChanges),revealedFacts:stringList(s.revealedFacts),openThreads:stringList(s.openThreads),foreshadowing:stringList(s.foreshadowing),endingState:clean(s.endingState),sourceRevision:Number(s.sourceRevision)||0,sourceHash:clean(s.sourceHash),generatedAt:s.generatedAt||''};}
  function normalizeState(s={}){return{storyOverview:clean(s.storyOverview),currentSituation:clean(s.currentSituation),characterStates:normalizeObjectList(s.characterStates),relationships:normalizeObjectList(s.relationships),timeline:stringList(s.timeline),openThreads:stringList(s.openThreads),foreshadowing:stringList(s.foreshadowing),revealedFacts:stringList(s.revealedFacts),locations:stringList(s.locations),lastUpdatedAt:s.lastUpdatedAt||'',sourceChapterRevisions:s.sourceChapterRevisions&&typeof s.sourceChapterRevisions==='object'?{...s.sourceChapterRevisions}:{},manualOverrides:s.manualOverrides&&typeof s.manualOverrides==='object'?clone(s.manualOverrides):{}};}
  function parsePayload(raw){if(raw&&typeof raw==='object')return raw;let s=String(raw||'').trim();s=s.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');return JSON.parse(s);}
  function validateAnalysisPayload(raw){const p=parsePayload(raw);if(!p||typeof p!=='object')throw new Error('剧情分析不是 JSON 对象');const summary=normalizeSummary(p.summary||p.chapterSummary||{}),delta=p.delta&&typeof p.delta==='object'?p.delta:(p.narrativeDelta&&typeof p.narrativeDelta==='object'?p.narrativeDelta:{});if(!summary.overview&&!summary.events.length&&!summary.endingState)throw new Error('章节摘要缺少可用内容');return{summary,delta};}
  function uniqStrings(a,b){return[...new Set([...stringList(a),...stringList(b)])];}
  function objectKey(x,kind){if(kind==='relationship')return `${x.from||x.a||x.source||''}|${x.to||x.b||x.target||''}`;return String(x.name||x.character||x.characterName||x.id||JSON.stringify(x));}
  function mergeObjectList(oldList,newList,kind){const map=new Map;for(const x of [...normalizeObjectList(oldList),...normalizeObjectList(newList)]){const k=objectKey(x,kind);if(!k)continue;map.set(k,{...(map.get(k)||{}),...x});}return[...map.values()];}
  function mergeDelta(stateInput,delta={},chapter={}){const s=normalizeState(stateInput);if(delta.storyOverview)s.storyOverview=clean(delta.storyOverview);if(delta.currentSituation)s.currentSituation=clean(delta.currentSituation);s.characterStates=mergeObjectList(s.characterStates,delta.characterStates,'character');s.relationships=mergeObjectList(s.relationships,delta.relationships,'relationship');s.timeline=uniqStrings(s.timeline,delta.timeline);s.openThreads=uniqStrings(s.openThreads,delta.openThreads);s.foreshadowing=uniqStrings(s.foreshadowing,delta.foreshadowing);s.revealedFacts=uniqStrings(s.revealedFacts,delta.revealedFacts);s.locations=uniqStrings(s.locations,delta.locations);for(const closed of stringList(delta.closedThreads))s.openThreads=s.openThreads.filter(x=>x!==closed);for(const resolved of stringList(delta.resolvedForeshadowing))s.foreshadowing=s.foreshadowing.filter(x=>x!==resolved);if(chapter?.id)s.sourceChapterRevisions[chapter.id]=Number(chapter.revision)||0;s.lastUpdatedAt=nowIso();return applyManualPatch(s,s.manualOverrides);}
  function isSummaryStale(chapter){if(!chapter)return true;const text=root.MimaNovelEngine?.getChapterText?.(chapter)||'';const hash=root.MimaNovelEngine?.hashText?.(text)||'';return !chapter.summarySourceRevision||Number(chapter.summarySourceRevision)!==Number(chapter.revision)||String(chapter.summarySourceHash||'')!==String(hash);}
  function invalidateFromChapter(project,chapterId){const idx=project.chapterOrder.indexOf(chapterId);if(idx<0)return project;for(let i=idx;i<project.chapterOrder.length;i++){const c=project.chapters.find(x=>x.id===project.chapterOrder[i]);if(c&&root.MimaNovelEngine?.getChapterText?.(c)?.trim())c.summaryStatus='stale';}project.memoryStatus={status:'stale',error:'',updatedAt:nowIso()};return project;}
  function applyManualPatch(stateInput,patch={}){const s=normalizeState(stateInput),p=patch&&typeof patch==='object'?patch:{};s.manualOverrides=clone(p);for(const key of ['storyOverview','currentSituation'])if(Object.prototype.hasOwnProperty.call(p,key))s[key]=clean(p[key]);for(const key of ['timeline','openThreads','foreshadowing','revealedFacts','locations'])if(Object.prototype.hasOwnProperty.call(p,key))s[key]=stringList(p[key]);for(const key of ['characterStates','relationships'])if(Object.prototype.hasOwnProperty.call(p,key))s[key]=normalizeObjectList(p[key]);return s;}
  function seedForRebuild(input={}){const s=normalizeState(input);return applyManualPatch(normalizeState({manualOverrides:s.manualOverrides}),s.manualOverrides);}
  root.MimaNovelMemory={normalizeSummary,normalizeState,validateAnalysisPayload,mergeDelta,isSummaryStale,invalidateFromChapter,applyManualPatch,seedForRebuild};
})();
