/** MimaTAVERN v1.3.0 Novel domain pure helpers. */
(() => {
  'use strict';
  const root=typeof window!=='undefined'?window:globalThis;
  const nowIso=()=>new Date().toISOString();
  const makeId=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;
  const arr=v=>Array.isArray(v)?v:[];
  const clone=v=>JSON.parse(JSON.stringify(v));
  const clean=v=>String(v??'').replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'');
  function hashText(input){let h=2166136261;const s=String(input??'');for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0');}
  function countVisibleChars(input){return String(input??'').replace(/<[^>]*>/g,'').replace(/[\s\u200B-\u200D\uFEFF]/g,'').length;}
  const chapterHeading=/^(?:(?:第\s*[0-9０-９一二三四五六七八九十百千〇零两]+\s*(?:章|回|节|卷)(?:\s*.*)?)|(?:卷\s*[0-9０-９一二三四五六七八九十百千〇零两]+(?:\s*.*)?)|(?:chapter\s+(?:\d+|[ivxlcdm]+)\b.*)|(?:序章|楔子|终章|后记|尾声)(?:\s*[：:·、—\-].*)?|(?:[0-9０-９]{1,3}[.、．]\s*[^\n]{1,58}))$/iu;
  function parseChapters(textInput){
    const text=clean(textInput).trim();if(!text)return[{title:'正文',content:''}];
    const lines=text.split('\n'),heads=[];for(let i=0;i<lines.length;i++){const line=lines[i].trim().replace(/^(?:[＃#]{1,5}\s*|[【〖（(]\s*)/u,'').replace(/[】〗）)]$/u,'').trim();if(line&&line.length<=80&&chapterHeading.test(line))heads.push({i,title:line});}
    if(!heads.length)return[{title:'正文',content:text}];
    const out=[];if(heads[0].i>0){const pre=lines.slice(0,heads[0].i).join('\n').trim();if(pre)out.push({title:'序章',content:pre});}
    for(let n=0;n<heads.length;n++){const h=heads[n],end=heads[n+1]?.i??lines.length;out.push({title:h.title,content:lines.slice(h.i+1,end).join('\n').trim()});}
    return out.length?out:[{title:'正文',content:text}];
  }
  function emptySummary(){return{overview:'',events:[],characterChanges:[],revealedFacts:[],openThreads:[],foreshadowing:[],endingState:'',sourceRevision:0,sourceHash:'',generatedAt:''};}
  function normalizeSegment(s={}){const t=s.createdAt||nowIso();return{id:s.id||makeId('seg'),kind:['source','ai_accepted','manual'].includes(s.kind)?s.kind:'manual',content:clean(s.content),createdAt:t,updatedAt:s.updatedAt||t,generationId:s.generationId||null};}
  function normalizeChapter(c={},projectId=''){const t=c.createdAt||nowIso();const segments=arr(c.segments).map(normalizeSegment);return{id:c.id||makeId('chap'),projectId:c.projectId||projectId,title:String(c.title||'正文').trim()||'正文',order:Number.isFinite(Number(c.order))?Number(c.order):0,segments,revision:Math.max(1,Number(c.revision)||1),summary:{...emptySummary(),...(c.summary&&typeof c.summary==='object'?c.summary:{})},summarySourceRevision:Number(c.summarySourceRevision)||0,summarySourceHash:String(c.summarySourceHash||''),summaryStatus:['fresh','stale','missing'].includes(c.summaryStatus)?c.summaryStatus:(c.summarySourceRevision?'fresh':'missing'),memoryDelta:c.memoryDelta&&typeof c.memoryDelta==='object'?clone(c.memoryDelta):null,createdAt:t,updatedAt:c.updatedAt||t};}
  function normalizeDraft(d={}){const t=d.createdAt||nowIso();return{id:d.id||makeId('draft'),projectId:d.projectId||'',chapterId:d.chapterId||'',generationId:d.generationId||'',content:clean(d.content),status:['generating','ready','interrupted','incomplete','rejected','accepted'].includes(d.status)?d.status:'generating',createdAt:t,updatedAt:d.updatedAt||t,metadata:d.metadata&&typeof d.metadata==='object'?d.metadata:{}};}
  function normalizeGeneration(g={}){const t=g.startedAt||nowIso();return{id:g.id||makeId('gen'),projectId:g.projectId||'',chapterId:g.chapterId||'',status:['generating','ready','interrupted','incomplete','rejected','accepted','failed'].includes(g.status)?g.status:'generating',directorNote:String(g.directorNote||''),minimumChars:Math.max(0,Number(g.minimumChars)||0),attempts:arr(g.attempts),startedAt:t,completedAt:g.completedAt||'',draftId:g.draftId||'',inputSnapshot:g.inputSnapshot&&typeof g.inputSnapshot==='object'?g.inputSnapshot:{},error:String(g.error||'')};}
  function defaultAppearance(a={}){return{fontFamily:String(a.fontFamily||''),fontSize:Number(a.fontSize)||17,lineHeight:Number(a.lineHeight)||1.9,letterSpacing:Number(a.letterSpacing)||0,paragraphGap:Number(a.paragraphGap)||1,firstLineIndent:Number.isFinite(Number(a.firstLineIndent))?Number(a.firstLineIndent):2,maxWidth:Number(a.maxWidth)||760,customCssId:a.customCssId||null,customCssEnabled:a.customCssEnabled!==false};}
  function normalizeProject(p={}){const t=p.createdAt||nowIso(),projectId=p.id||makeId('novel');let chapters=arr(p.chapters).map(c=>normalizeChapter(c,projectId));if(!chapters.length)chapters=[normalizeChapter({title:'正文',order:0,segments:[]},projectId)];chapters.sort((a,b)=>a.order-b.order);chapters.forEach((c,i)=>{c.order=i;c.projectId=projectId});const order=arr(p.chapterOrder).filter(id=>chapters.some(c=>c.id===id));for(const c of chapters)if(!order.includes(c.id))order.push(c.id);const active=order.includes(p.activeChapterId)?p.activeChapterId:order[order.length-1];return{id:projectId,recordRevision:Math.max(0,Number(p.recordRevision)||0),title:String(p.title||'未命名小说').trim()||'未命名小说',createdAt:t,updatedAt:p.updatedAt||t,sourceName:String(p.sourceName||''),sourceEncoding:String(p.sourceEncoding||'utf-8'),sourceText:clean(p.sourceText),sourceHash:String(p.sourceHash||hashText(p.sourceText||'')),chapters,chapterOrder:order,activeChapterId:active,presetIds:arr(p.presetIds).map(String),worldbookIds:arr(p.worldbookIds).map(String),modelSettings:{model:String(p.modelSettings?.model||''),temperature:p.modelSettings?.temperature===null||p.modelSettings?.temperature===undefined?null:(Number.isFinite(Number(p.modelSettings.temperature))?Number(p.modelSettings.temperature):null),sendTemperature:typeof p.modelSettings?.sendTemperature==='boolean'?p.modelSettings.sendTemperature:null,streaming:typeof p.modelSettings?.streaming==='boolean'?p.modelSettings.streaming:null,maxTokens:Math.max(0,Number(p.modelSettings?.maxTokens)||0)},generationSettings:{minimumChars:Math.max(0,Number(p.generationSettings?.minimumChars)||1200),maxAppendAttempts:Number.isFinite(Number(p.generationSettings?.maxAppendAttempts))?Math.max(0,Math.min(8,Number(p.generationSettings.maxAppendAttempts))):3,contextBudgetChars:Math.max(4000,Number(p.generationSettings?.contextBudgetChars)||48000)},narrativeState:p.narrativeState&&typeof p.narrativeState==='object'?p.narrativeState:{},legacyNarrativeCheckpoint:Object.prototype.hasOwnProperty.call(p,'legacyNarrativeCheckpoint')?p.legacyNarrativeCheckpoint:(root.MimaNovelMemory?.prepareLegacyCheckpoint?.(p)||null),memoryStatus:p.memoryStatus&&typeof p.memoryStatus==='object'?p.memoryStatus:{status:'missing',error:'',updatedAt:''},drafts:arr(p.drafts).map(normalizeDraft),generations:arr(p.generations).map(normalizeGeneration),appearance:defaultAppearance(p.appearance),createdFrom:p.createdFrom||'manual'};}
  function createProjectFromText({title,sourceName='',sourceEncoding='utf-8',text=''}){const id=makeId('novel'),parts=parseChapters(text),createdAt=nowIso();const chapters=parts.map((part,i)=>normalizeChapter({id:makeId('chap'),projectId:id,title:part.title,order:i,segments:[normalizeSegment({kind:'source',content:part.content,createdAt})],createdAt,updatedAt:createdAt},id));return normalizeProject({id,title:title||sourceName.replace(/\.[^.]+$/,'')||'未命名小说',createdAt,updatedAt:createdAt,sourceName,sourceEncoding,sourceText:clean(text),sourceHash:hashText(clean(text)),chapters,chapterOrder:chapters.map(c=>c.id),activeChapterId:chapters[chapters.length-1]?.id||null,createdFrom:'txt_import'});}
  function orderedChapters(p){const project=normalizeProject(p);return project.chapterOrder.map(id=>project.chapters.find(c=>c.id===id)).filter(Boolean);}
  function getChapter(p,id){return arr(p?.chapters).find(c=>c.id===id)||null;}
  function getChapterText(c){return arr(c?.segments).map(s=>String(s.content||'')).filter(Boolean).join('\n\n').trim();}
  function chapterHash(c){return hashText(getChapterText(c));}
  function markProjectStale(p,startId){const idx=p.chapterOrder.indexOf(startId);if(idx<0)return;for(let i=idx;i<p.chapterOrder.length;i++){const c=getChapter(p,p.chapterOrder[i]);if(c&&getChapterText(c).trim())c.summaryStatus='stale';}p.memoryStatus={status:'stale',error:'',updatedAt:nowIso()};}
  function editChapter(projectInput,chapterId,action,payload={}){const p=normalizeProject(clone(projectInput)),c=getChapter(p,chapterId);if(!c)throw new Error('未找到章节');const idx=p.chapterOrder.indexOf(c.id);
    if(action==='rename'){c.title=String(payload.title||'').trim()||c.title;c.updatedAt=nowIso();}
    else if(action==='replace_text'){c.segments=[normalizeSegment({kind:'manual',content:String(payload.content??''),createdAt:nowIso()})];c.revision++;c.updatedAt=nowIso();markProjectStale(p,c.id);}
    else if(action==='split'){const text=getChapterText(c),at=Math.max(1,Math.min(text.length-1,Number(payload.index)||Math.floor(text.length/2)));const left=text.slice(0,at).trim(),right=text.slice(at).trim();if(!right)throw new Error('拆分位置没有后半段正文');c.segments=[normalizeSegment({kind:'manual',content:left})];c.revision++;const nc=normalizeChapter({projectId:p.id,title:String(payload.title||`${c.title}（续）`),segments:[normalizeSegment({kind:'manual',content:right})]},p.id);p.chapters.push(nc);p.chapterOrder.splice(idx+1,0,nc.id);markProjectStale(p,c.id);}
    else if(action==='merge_next'){const nextId=p.chapterOrder[idx+1],n=getChapter(p,nextId);if(!n)throw new Error('没有下一章可合并');c.segments=[...c.segments,...n.segments.map(normalizeSegment)];c.revision++;p.chapters=p.chapters.filter(x=>x.id!==n.id);p.chapterOrder.splice(idx+1,1);if(p.activeChapterId===n.id)p.activeChapterId=c.id;for(const d of p.drafts){if(d.chapterId===n.id){d.chapterId=c.id;d.metadata={...d.metadata,mergedFromChapterId:n.id,requiresRebase:true};}}for(const g of p.generations){if(g.chapterId===n.id){g.chapterId=c.id;g.inputSnapshot={...g.inputSnapshot,mergedFromChapterId:n.id,requiresRebase:true};}}markProjectStale(p,c.id);}
    else if(action==='edit_segment'){const seg=c.segments.find(s=>s.id===payload.segmentId);if(!seg)throw new Error('找不到该原文/续写片段');const next=clean(payload.content);if(!next.trim())throw new Error('片段不能保存为空');if(seg.content!==next){seg.content=next;seg.updatedAt=nowIso();c.revision++;c.updatedAt=nowIso();markProjectStale(p,c.id);}}
    else if(action==='move'){const to=Math.max(0,Math.min(p.chapterOrder.length-1,Number(payload.toIndex)||0));p.chapterOrder.splice(idx,1);p.chapterOrder.splice(to,0,c.id);markProjectStale(p,p.chapterOrder[Math.min(idx,to)]||c.id);}
    else if(action==='delete'){if(p.chapterOrder.length<=1)throw new Error('小说至少需要保留一个章节');p.chapters=p.chapters.filter(x=>x.id!==c.id);p.chapterOrder.splice(idx,1);p.drafts=p.drafts.filter(x=>x.chapterId!==c.id);p.generations=p.generations.filter(x=>x.chapterId!==c.id);const staleFrom=Math.max(0,Math.min(idx,p.chapterOrder.length-1));for(let i=staleFrom;i<p.chapterOrder.length;i++){const later=getChapter(p,p.chapterOrder[i]);if(later&&getChapterText(later).trim())later.summaryStatus='stale';}p.memoryStatus={status:'stale',error:'',updatedAt:nowIso()};if(p.activeChapterId===c.id)p.activeChapterId=p.chapterOrder[staleFrom]||p.chapterOrder[staleFrom-1]||null;}
    else throw new Error(`未知章节操作：${action}`);
    p.chapterOrder.forEach((id,i)=>{const ch=getChapter(p,id);if(ch)ch.order=i});p.updatedAt=nowIso();return normalizeProject(p);
  }
  function appendNewChapter(projectInput,title=''){
    const p=normalizeProject(clone(projectInput));const number=p.chapterOrder.map(id=>getChapter(p,id)).filter(c=>c&&/^(?:第\s*.+?\s*章|chapter\s+)/iu.test(c.title)).length+1;const c=normalizeChapter({projectId:p.id,title:String(title||`第${number}章`).trim(),order:p.chapterOrder.length,segments:[]},p.id);
    p.chapters.push(c);p.chapterOrder.push(c.id);p.activeChapterId=c.id;p.updatedAt=nowIso();return normalizeProject(p);
  }
  function reparseImportedProject(projectInput){
    const p=normalizeProject(clone(projectInput));
    if(p.createdFrom!=='txt_import'||!p.sourceText.trim())throw new Error('只支持重新识别原 TXT 导入的小说');
    if(p.generations.length||p.drafts.length||p.chapters.some(c=>c.revision!==1||c.segments.some(s=>s.kind!=='source')))throw new Error('项目已有人工修改或续写记录，不能自动覆盖章节；请使用手动拆章。');
    const found=parseChapters(p.sourceText);if(found.length<=1)throw new Error('未识别到多个可靠章节标题，请用手动拆章。');
    const rebuilt=createProjectFromText({title:p.title,sourceName:p.sourceName,sourceEncoding:p.sourceEncoding,text:p.sourceText});
    p.chapters=rebuilt.chapters.map(c=>({...c,projectId:p.id}));p.chapterOrder=p.chapters.map(c=>c.id);p.activeChapterId=p.chapterOrder[p.chapterOrder.length-1];
    p.narrativeState={};p.memoryStatus={status:'missing',error:'',updatedAt:nowIso()};p.updatedAt=nowIso();return normalizeProject(p);
  }
  function appendDraftText(before,chunk){const a=String(before||''),b=String(chunk||'');if(!a)return b;if(!b)return a;const max=Math.min(a.length,b.length,400);let overlap=0;for(let i=max;i>8;i--){if(a.slice(-i)===b.slice(0,i)){overlap=i;break}}return a+b.slice(overlap);}
  function appendAcceptedSegment(projectInput,chapterId,draft){const p=normalizeProject(clone(projectInput)),c=getChapter(p,chapterId);if(!c)throw new Error('未找到章节');const content=String(draft?.content||'').trim();if(!content)throw new Error('草稿为空，不能采纳');c.segments.push(normalizeSegment({kind:'ai_accepted',content,generationId:draft.generationId}));c.revision++;c.updatedAt=nowIso();markProjectStale(p,c.id);p.updatedAt=nowIso();return p;}
  function exportProjectText(projectInput){const p=normalizeProject(projectInput);return orderedChapters(p).map(c=>`${c.title}\n\n${getChapterText(c)}`.trim()).join('\n\n\n').trim()+"\n";}
  root.MimaNovelEngine={hashText,countVisibleChars,parseChapters,normalizeProject,normalizeChapter,normalizeSegment,normalizeDraft,normalizeGeneration,createProjectFromText,getChapter,getChapterText,chapterHash,orderedChapters,editChapter,appendNewChapter,reparseImportedProject,appendDraftText,exportProjectText,appendAcceptedSegment,makeId,nowIso,clone};
})();
